# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighborHood',
            new_name='neighborhood',
        ),
    ]
