# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-08 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0002_auto_20190708_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighborhood',
            new_name='neighborHood',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='neighborhood',
            new_name='neighborHood',
        ),
    ]
